# Generated by Django 5.1.2 on 2024-11-14 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DiningHall",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("location_id", models.IntegerField(unique=True)),
                ("name", models.CharField(max_length=200)),
                ("opening_hours", models.TimeField(blank=True, null=True)),
                ("closing_hours", models.TimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.IntegerField(unique=True)),
                ("planner_id", models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Menu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("meal_name", models.CharField(max_length=100)),
                ("category_name", models.CharField(max_length=100)),
                ("menu_date", models.DateField()),
                (
                    "dining_hall",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="meal_db.dininghall",
                    ),
                ),
            ],
            options={
                "unique_together": {("dining_hall", "meal_name", "menu_date")},
            },
        ),
        migrations.CreateModel(
            name="Food",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dish_name", models.CharField(max_length=200)),
                ("healthfulness", models.IntegerField(blank=True, null=True)),
                ("carbon_list", models.CharField(blank=True, max_length=10, null=True)),
                ("ingredient_list", models.JSONField(default=list)),
                ("allergens", models.JSONField(default=list)),
                (
                    "recipe_webcode",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("diets", models.JSONField(default=list)),
                (
                    "serving_size",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("calories", models.IntegerField(blank=True, null=True)),
                ("calories_from_fat", models.IntegerField(blank=True, null=True)),
                ("total_fat", models.CharField(blank=True, max_length=50, null=True)),
                ("sat_fat", models.CharField(blank=True, max_length=50, null=True)),
                ("trans_fat", models.CharField(blank=True, max_length=50, null=True)),
                ("cholesterol", models.CharField(blank=True, max_length=50, null=True)),
                ("sodium", models.CharField(blank=True, max_length=50, null=True)),
                ("total_carb", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "dietary_fiber",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("sugars", models.CharField(blank=True, max_length=50, null=True)),
                ("protein", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "menu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="meal_db.menu"
                    ),
                ),
            ],
        ),
    ]
