# Generated by Django 5.1.2 on 2024-10-23 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meal_db", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DiningHall",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Food",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("calories", models.IntegerField()),
                ("carbs", models.FloatField()),
                ("proteins", models.FloatField()),
                ("fats", models.FloatField()),
                ("calcium", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="Menu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "time_slot",
                    models.CharField(
                        choices=[
                            ("breakfast", "Breakfast"),
                            ("lunch", "Lunch"),
                            ("brunch", "Brunch"),
                            ("dinner", "Dinner"),
                            ("late night", "Late Night"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "dining_hall",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="menus",
                        to="meal_db.dininghall",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("userID", models.IntegerField()),
                ("plannerID", models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name="Teacher",
        ),
        migrations.AddField(
            model_name="food",
            name="menu",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="foods",
                to="meal_db.menu",
            ),
        ),
    ]
