# Generated by Django 5.1.2 on 2024-10-27 20:45

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal_db', '0002_dininghall_food_menu_user_delete_teacher_food_menu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='calcium',
        ),
        migrations.RemoveField(
            model_name='food',
            name='menu',
        ),
        migrations.AddField(
            model_name='menu',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='menu',
            name='day_of_week',
            field=models.CharField(blank=True, choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='menu',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='menu',
            name='foods',
            field=models.ManyToManyField(related_name='menus', to='meal_db.food'),
        ),
        migrations.AddField(
            model_name='menu',
            name='is_special',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='food',
            name='calories',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='food',
            name='carbs',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='food',
            name='fats',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='food',
            name='proteins',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterUniqueTogether(
            name='menu',
            unique_together={('dining_hall', 'time_slot', 'date', 'day_of_week')},
        ),
        migrations.CreateModel(
            name='MealCombination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calories', models.FloatField()),
                ('proteins', models.FloatField()),
                ('fats', models.FloatField()),
                ('carbs', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('foods', models.ManyToManyField(related_name='meal_combinations', to='meal_db.food')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_combinations', to='meal_db.menu')),
            ],
        ),
    ]
